# Permalinks
permalink:        pretty

# Setup
url:              

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          /blog

title:            Manticoa

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  그냥 이것저것 쓰고있습니다.
# The tags listed as entries in the sidebar
sidebar_tags:     [android,tech,talk]

# Fallback image and color if not overwritten for tag or post
image:            public/img/sakura.jpg
color:            '#A85641'

author:
  name:           'Kim HanSung'
  twitter:        malzeve
  github:         manticoa
  photo:          http://qwtel.com/public/img/flo.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm Florian or [`@qwtel`](https://www.twitter.com/qwtel), which isn't an acronym,
    I just [wanted a short username](http://qwtel.com/how-to-find-a-short-username) and that one happened to be available.

    Read my thoughts on [#software](http://qwtel.com/tag/software) and [#cryptoeconomics](http://qwtel.com/tag/cryptoeconomics).
